### ISSUE TITLE
An internal error occured.

### ISSUE THREAD

**Issue by ghost** [BlazingBroGamer/Staff-Essentials#4]
I keep getting this message in game.

_An internal error occurred while attempting to perform this command._

I keep getting this message in the console.

_[02:53:54 WARN]: [StaffEssentials] Task #17 for StaffEssentials v1.1.4 generated an exception
java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_192]
at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_192]
at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_192]
at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_192]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.12.2.jar:git-Paper-1554]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1554]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
at me.BlazingBroGamer.StaffEssentials.BanMuteManager$1.run(BanMuteManager.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1554]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1554]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1554]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1554]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1554]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1554]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]_

Server Version: 1.12.2 (I use Viaverson, Backwards, and Rewind for 1.7-1.13.2 support.)
Plugin Version: 1.1.4

**Comment by DeltaKilo97** [comment]
I am also getting "An internal error occurred while attempting to perform this command"; while restarting the server, I am getting this error

[Console Shown Below]
> [24-Jul-2019 02:09:11] Error occurred while enabling StaffEssentials v1.1.4 (Is it up to date?)
>[24-Jul-2019 02:09:11] java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/World
>[24-Jul-2019 02:09:11] at me.BlazingBroGamer.StaffEssentials.Commands.InventoryCheckCommand.<init>(InventoryCheckCommand.java:17) ~[?:?]
>[24-Jul-2019 02:09:11] at me.BlazingBroGamer.StaffEssentials.StaffEssentials.registerCommands(StaffEssentials.java:169) ~>[?:?]
[24-Jul-2019 02:09:11] at me.BlazingBroGamer.StaffEssentials.StaffEssentials.onEnable(StaffEssentials.java:64) ~[?:?]
[24-Jul-2019 02:09:11] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[24-Jul-2019 02:09:11] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.World
[24-Jul-2019 02:09:11] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-136]
[24-Jul-2019 02:09:11] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
[24-Jul-2019 02:09:11] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
[24-Jul-2019 02:09:11] ... 12 more
[24-Jul-2019 02:09:11] [StaffEssentials] Disabling StaffEssentials v1.1.4
